name: Android CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/android

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew assembleDebug --stacktrace

      - name: Unit Test
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Lint
        run: ./gradlew lintDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: frontend/app/build/outputs/apk/debug/*.apk

